<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $all_languages = [
            ["en_name" => "Abkhazian", "iso" => "ab", "ar_name" => "الأبخازية"],
            ["en_name" => "Afar", "iso" => "aa", "ar_name" => "لغة عفارية"],
            ["en_name" => "Afrikaans", "iso" => "af", "ar_name" => "الأفريكانية"],
            ["en_name" => "Akan", "iso" => "ak", "ar_name" => "اكان"],
            ["en_name" => "Albanian", "iso" => "sq", "ar_name" => "الألبانية"],
            ["en_name" => "Amharic", "iso" => "am", "ar_name" => "الأمهرية"],
            ["en_name" => "Arabic", "iso" => "ar", "ar_name" => "عربي"],
            ["en_name" => "Aragonese", "iso" => "an", "ar_name" => "أراغون"],
            ["en_name" => "Armenian", "iso" => "hy", "ar_name" => "الأرمينية"],
            ["en_name" => "Assamese", "iso" => "as", "ar_name" => "الأسامية"],
            ["en_name" => "Avaric", "iso" => "av", "ar_name" => "افاريك"],
            ["en_name" => "Avestan", "iso" => "ae", "ar_name" => "أفستان"],
            ["en_name" => "Aymara", "iso" => "ay", "ar_name" => "ايمارا"],
            ["en_name" => "Azerbaijani", "iso" => "az", "ar_name" => "أذربيجاني"],
            ["en_name" => "Bambara", "iso" => "bm", "ar_name" => "بامبارا"],
            ["en_name" => "Bashkir", "iso" => "ba", "ar_name" => "بشكير"],
            ["en_name" => "Basque", "iso" => "eu", "ar_name" => "الباسك"],
            ["en_name" => "Belarusian", "iso" => "be", "ar_name" => "البيلاروسية"],
            ["en_name" => "Bengali", "iso" => "bn", "ar_name" => "البنغالية"],
            ["en_name" => "Bislama", "iso" => "bi", "ar_name" => "بيسلاما"],
            ["en_name" => "Bosnian", "iso" => "bs", "ar_name" => "البوسنية"],
            ["en_name" => "Breton", "iso" => "br", "ar_name" => "بريتون"],
            ["en_name" => "Bulgarian", "iso" => "bg", "ar_name" => "البلغارية"],
            ["en_name" => "Burmese", "iso" => "my", "ar_name" => "البورمية"],
            ["en_name" => "Catalan, Valencian", "iso" => "ca", "ar_name" => "الكاتالونية، بلنسية"],
            ["en_name" => "Chamorro", "iso" => "ch", "ar_name" => "تشامورو"],
            ["en_name" => "Chechen", "iso" => "ce", "ar_name" => "الشيشانية"],
            ["en_name" => "Chichewa, Chewa, Nyanja", "iso" => "ny", "ar_name" => "تشيتشيوا، تشيوا، نيانجا"],
            ["en_name" => "Chinese", "iso" => "zh", "ar_name" => "صينى"],
            ["en_name" => "Church Slavonic, Old Slavonic, Old Church Slavonic", "iso" => "cu", "ar_name" => "السلافية الكنسية، السلافية القديمة، السلافية الكنسية القديمة"],
            ["en_name" => "Chuvash", "iso" => "cv", "ar_name" => "تشوفاش"],
            ["en_name" => "Cornish", "iso" => "kw", "ar_name" => "الكورنيش"],
            ["en_name" => "Corsican", "iso" => "co", "ar_name" => "كورسيكية"],
            ["en_name" => "Cree", "iso" => "cr", "ar_name" => "كري"],
            ["en_name" => "Croatian", "iso" => "hr", "ar_name" => "الكرواتية"],
            ["en_name" => "Czech", "iso" => "cs", "ar_name" => "التشيكية"],
            ["en_name" => "Danish", "iso" => "da", "ar_name" => "دانماركي"],
            ["en_name" => "Divehi, Dhivehi, Maldivian", "iso" => "dv", "ar_name" => "ديفيهي، ديفيهي، جزر المالديف"],
            ["en_name" => "Dutch, Flemish", "iso" => "nl", "ar_name" => "الهولندية، الفلمنكية"],
            ["en_name" => "Dzongkha", "iso" => "dz", "ar_name" => "دزونغخا"],
            ["en_name" => "English", "iso" => "en", "ar_name" => "إنجليزي"],
            ["en_name" => "Esperanto", "iso" => "eo", "ar_name" => "الاسبرانتو"],
            ["en_name" => "Estonian", "iso" => "et", "ar_name" => "الإستونية"],
            ["en_name" => "Ewe", "iso" => "ee", "ar_name" => "نعجة"],
            ["en_name" => "Faroese", "iso" => "fo", "ar_name" => "جزر فارو"],
            ["en_name" => "Fijian", "iso" => "fj", "ar_name" => "فيجي"],
            ["en_name" => "Finnish", "iso" => "fi", "ar_name" => "الفنلندية"],
            ["en_name" => "French", "iso" => "fr", "ar_name" => "فرنسي"],
            ["en_name" => "Western Frisian", "iso" => "fy", "ar_name" => "الفريزية الغربية"],
            ["en_name" => "Fulah", "iso" => "ff", "ar_name" => "فولا"],
            ["en_name" => "Gaelic, Scottish Gaelic", "iso" => "gd", "ar_name" => "الغيلية، الغيلية الاسكتلندية"],
            ["en_name" => "Galician", "iso" => "gl", "ar_name" => "الجاليكية"],
            ["en_name" => "Ganda", "iso" => "lg", "ar_name" => "غاندا"],
            ["en_name" => "Georgian", "iso" => "ka", "ar_name" => "الجورجية"],
            ["en_name" => "German", "iso" => "de", "ar_name" => "ألمانية"],
            ["en_name" => "Greek, Modern (1453–)", "iso" => "el", "ar_name" => "اليونانية الحديثة (1453–)"],
            ["en_name" => "Kalaallisut, Greenlandic", "iso" => "kl", "ar_name" => "كالاليسوت، جرينلاند"],
            ["en_name" => "Guarani", "iso" => "gn", "ar_name" => "الغواراني"],
            ["en_name" => "Gujarati", "iso" => "gu", "ar_name" => "الغوجاراتية"],
            ["en_name" => "Haitian, Haitian Creole", "iso" => "ht", "ar_name" => "الهايتية، الكريول الهايتية"],
            ["en_name" => "Hausa", "iso" => "ha", "ar_name" => "الهوسا"],
            ["en_name" => "Hebrew", "iso" => "he", "ar_name" => "اللغة العبرية"],
            ["en_name" => "Herero", "iso" => "hz", "ar_name" => "هيريرو"],
            ["en_name" => "Hindi", "iso" => "hi", "ar_name" => "الهندية"],
            ["en_name" => "Hiri Motu", "iso" => "ho", "ar_name" => "هيري موتو"],
            ["en_name" => "Hungarian", "iso" => "hu", "ar_name" => "المجرية"],
            ["en_name" => "Icelandic", "iso" => "is", "ar_name" => "الأيسلندية"],
            ["en_name" => "Ido", "iso" => "io", "ar_name" => "أفعل"],
            ["en_name" => "Igbo", "iso" => "ig", "ar_name" => "الإيغبو"],
            ["en_name" => "Indonesian", "iso" => "id", "ar_name" => "الاندونيسية"],
            ["en_name" => "Interlingua (International Auxiliary Language Association)", "iso" => "ia", "ar_name" => "Interlingua (الرابطة الدولية للغات المساعدة)"],
            ["en_name" => "Interlingue, Occidental", "iso" => "ie", "ar_name" => "Interlingue، أوكسيدنتال"],
            ["en_name" => "Inuktitut", "iso" => "iu", "ar_name" => "إنكتيتوت"],
            ["en_name" => "Inupiaq", "iso" => "ik", "ar_name" => "اينوبياك"],
            ["en_name" => "Irish", "iso" => "ga", "ar_name" => "الأيرلندية"],
            ["en_name" => "Italian", "iso" => "it", "ar_name" => "ايطالي"],
            ["en_name" => "Japanese", "iso" => "ja", "ar_name" => "اليابانية"],
            ["en_name" => "Javanese", "iso" => "jv", "ar_name" => "الجاوية"],
            ["en_name" => "Kannada", "iso" => "kn", "ar_name" => "الكانادا"],
            ["en_name" => "Kanuri", "iso" => "kr", "ar_name" => "كانوري"],
            ["en_name" => "Kashmiri", "iso" => "ks", "ar_name" => "الكشميري"],
            ["en_name" => "Kazakh", "iso" => "kk", "ar_name" => "الكازاخستانية"],
            ["en_name" => "Central Khmer", "iso" => "km", "ar_name" => "الخمير الوسطى"],
            ["en_name" => "Kikuyu, Gikuyu", "iso" => "ki", "ar_name" => "كيكويو، كيكويو"],
            ["en_name" => "Kinyarwanda", "iso" => "rw", "ar_name" => "الكينيارواندية"],
            ["en_name" => "Kirghiz, Kyrgyz", "iso" => "ky", "ar_name" => "قيرغيزستان، قيرغيزستان"],
            ["en_name" => "Komi", "iso" => "kv", "ar_name" => "كومي"],
            ["en_name" => "Kongo", "iso" => "kg", "ar_name" => "الكونغو"],
            ["en_name" => "Korean", "iso" => "ko", "ar_name" => "الكورية"],
            ["en_name" => "Kuanyama, Kwanyama", "iso" => "kj", "ar_name" => "كوانياما، كوانياما"],
            ["en_name" => "Kurdish", "iso" => "ku", "ar_name" => "كردي"],
            ["en_name" => "Lao", "iso" => "lo", "ar_name" => "لاو"],
            ["en_name" => "Latin", "iso" => "la", "ar_name" => "اللاتينية"],
            ["en_name" => "Latvian", "iso" => "lv", "ar_name" => "لاتفيا"],
            ["en_name" => "Limburgan, Limburger, Limburgish", "iso" => "li", "ar_name" => "ليمبورجان، ليمبرجر، ليمبورجيش"],
            ["en_name" => "Lingala", "iso" => "ln", "ar_name" => "اللينجالا"],
            ["en_name" => "Lithuanian", "iso" => "lt", "ar_name" => "الليتوانية"],
            ["en_name" => "Luba-Katanga", "iso" => "lu", "ar_name" => "لوبا كاتانغا"],
            ["en_name" => "Luxembourgish, Letzeburgesch", "iso" => "lb", "ar_name" => "اللوكسمبرجية، ليتزبورجيش"],
            ["en_name" => "Macedonian", "iso" => "mk", "ar_name" => "المقدونية"],
            ["en_name" => "Malagasy", "iso" => "mg", "ar_name" => "مدغشقر"],
            ["en_name" => "Malay", "iso" => "ms", "ar_name" => "لغة الملايو"],
            ["en_name" => "Malayalam", "iso" => "ml", "ar_name" => "المالايالامية"],
            ["en_name" => "Maltese", "iso" => "mt", "ar_name" => "المالطية"],
            ["en_name" => "Manx", "iso" => "gv", "ar_name" => "مانكس"],
            ["en_name" => "Maori", "iso" => "mi", "ar_name" => "الماوري"],
            ["en_name" => "Marathi", "iso" => "mr", "ar_name" => "المهاراتية"],
            ["en_name" => "Marshallese", "iso" => "mh", "ar_name" => "المارشالية"],
            ["en_name" => "Mongolian", "iso" => "mn", "ar_name" => "المنغولية"],
            ["en_name" => "Nauru", "iso" => "na", "ar_name" => "ناورو"],
            ["en_name" => "Navajo, Navaho", "iso" => "nv", "ar_name" => "نافاجو، نافاهو"],
            ["en_name" => "North Ndebele", "iso" => "nd", "ar_name" => "شمال نديبيلي"],
            ["en_name" => "South Ndebele", "iso" => "nr", "ar_name" => "جنوب نديبيلي"],
            ["en_name" => "Ndonga", "iso" => "ng", "ar_name" => "ندونجا"],
            ["en_name" => "Nepali", "iso" => "ne", "ar_name" => "النيبالية"],
            ["en_name" => "Norwegian", "iso" => "no", "ar_name" => "النرويجية"],
            ["en_name" => "Norwegian Bokmål", "iso" => "nb", "ar_name" => "البوكمال النرويجية"],
            ["en_name" => "Norwegian Nynorsk", "iso" => "nn", "ar_name" => "نينورسك النرويجي"],
            ["en_name" => "Sichuan Yi, Nuosu", "iso" => "ii", "ar_name" => "سيتشوان يي، نوسو"],
            ["en_name" => "Occitan", "iso" => "oc", "ar_name" => "الأوكيتانية"],
            ["en_name" => "Ojibwa", "iso" => "oj", "ar_name" => "اوجيبوا"],
            ["en_name" => "Oriya", "iso" => "or", "ar_name" => "أوريا"],
            ["en_name" => "Oromo", "iso" => "om", "ar_name" => "الأورومو"],
            ["en_name" => "Ossetian, Ossetic", "iso" => "os", "ar_name" => "أوسيتيا، أوسيتيا"],
            ["en_name" => "Pali", "iso" => "pi", "ar_name" => "بالي"],
            ["en_name" => "Pashto, Pushto", "iso" => "ps", "ar_name" => "الباشتو، الباشتو"],
            ["en_name" => "Persian", "iso" => "fa", "ar_name" => "اللغة الفارسية"],
            ["en_name" => "Polish", "iso" => "pl", "ar_name" => "تلميع"],
            ["en_name" => "Portuguese", "iso" => "pt", "ar_name" => "البرتغالية"],
            ["en_name" => "Punjabi, Panjabi", "iso" => "pa", "ar_name" => "البنجابية، البنجابية"],
            ["en_name" => "Quechua", "iso" => "qu", "ar_name" => "الكيشوا"],
            ["en_name" => "Romanian, Moldavian, Moldovan", "iso" => "ro", "ar_name" => "الرومانية، المولدافية، المولدوفية"],
            ["en_name" => "Romansh", "iso" => "rm", "ar_name" => "الرومانشية"],
            ["en_name" => "Rundi", "iso" => "rn", "ar_name" => "روندي"],
            ["en_name" => "Russian", "iso" => "ru", "ar_name" => "الروسية"],
            ["en_name" => "Northern Sami", "iso" => "se", "ar_name" => "سامي الشمالي"],
            ["en_name" => "Samoan", "iso" => "sm", "ar_name" => "ساموا"],
            ["en_name" => "Sango", "iso" => "sg", "ar_name" => "سانجو"],
            ["en_name" => "Sanskrit", "iso" => "sa", "ar_name" => "السنسكريتية"],
            ["en_name" => "Sardinian", "iso" => "sc", "ar_name" => "سردينيا"],
            ["en_name" => "Serbian", "iso" => "sr", "ar_name" => "الصربية"],
            ["en_name" => "Shona", "iso" => "sn", "ar_name" => "شونا"],
            ["en_name" => "Sindhi", "iso" => "sd", "ar_name" => "السندية"],
            ["en_name" => "Sinhala, Sinhalese", "iso" => "si", "ar_name" => "السنهالية، السنهالية"],
            ["en_name" => "Slovak", "iso" => "sk", "ar_name" => "السلوفاكية"],
            ["en_name" => "Slovenian", "iso" => "sl", "ar_name" => "السلوفينية"],
            ["en_name" => "Somali", "iso" => "so", "ar_name" => "الصومالية"],
            ["en_name" => "Southern Sotho", "iso" => "st", "ar_name" => "جنوب سوتو"],
            ["en_name" => "Spanish, Castilian", "iso" => "es", "ar_name" => "الإسبانية، القشتالية"],
            ["en_name" => "Sundanese", "iso" => "su", "ar_name" => "السودانية"],
            ["en_name" => "Swahili", "iso" => "sw", "ar_name" => "السواحلية"],
            ["en_name" => "Swati", "iso" => "ss", "ar_name" => "سواتي"],
            ["en_name" => "Swedish", "iso" => "sv", "ar_name" => "السويدية"],
            ["en_name" => "Tagalog", "iso" => "tl", "ar_name" => "التاغالوغية"],
            ["en_name" => "Tahitian", "iso" => "ty", "ar_name" => "تاهيتي"],
            ["en_name" => "Tajik", "iso" => "tg", "ar_name" => "الطاجيكية"],
            ["en_name" => "Tamil", "iso" => "ta", "ar_name" => "التاميل"],
            ["en_name" => "Tatar", "iso" => "tt", "ar_name" => "التتار"],
            ["en_name" => "Telugu", "iso" => "te", "ar_name" => "التيلجو"],
            ["en_name" => "Thai", "iso" => "th", "ar_name" => "التايلاندية"],
            ["en_name" => "Tibetan", "iso" => "bo", "ar_name" => "التبتية"],
            ["en_name" => "Tigrinya", "iso" => "ti", "ar_name" => "التغرينية"],
            ["en_name" => "Tonga (Tonga Islands)", "iso" => "to", "ar_name" => "تونغا (جزر تونغا)"],
            ["en_name" => "Tsonga", "iso" => "ts", "ar_name" => "تسونجا"],
            ["en_name" => "Tswana", "iso" => "tn", "ar_name" => "تسوانا"],
            ["en_name" => "Turkish", "iso" => "tr", "ar_name" => "اللغة التركية"],
            ["en_name" => "Turkmen", "iso" => "tk", "ar_name" => "التركمان"],
            ["en_name" => "Twi", "iso" => "tw", "ar_name" => "توي"],
            ["en_name" => "Uighur, Uyghur", "iso" => "ug", "ar_name" => "الإيغور، الإيغور"],
            ["en_name" => "Ukrainian", "iso" => "uk", "ar_name" => "الأوكرانية"],
            ["en_name" => "Urdu", "iso" => "ur", "ar_name" => "الأردية"],
            ["en_name" => "Uzbek", "iso" => "uz", "ar_name" => "الأوزبكية"],
            ["en_name" => "Venda", "iso" => "ve", "ar_name" => "فيندا"],
            ["en_name" => "Vietnamese", "iso" => "vi", "ar_name" => "الفيتنامية"],
            ["en_name" => "Volapük", "iso" => "vo", "ar_name" => "فولابوك"],
            ["en_name" => "Walloon", "iso" => "wa", "ar_name" => "الوالون"],
            ["en_name" => "Welsh", "iso" => "cy", "ar_name" => "تهرب من دفع الرهان"],
            ["en_name" => "Wolof", "iso" => "wo", "ar_name" => "الولوف"],
            ["en_name" => "Xhosa", "iso" => "xh", "ar_name" => "خوسا"],
            ["en_name" => "Yiddish", "iso" => "yi", "ar_name" => "اليديشية"],
            ["en_name" => "Yoruba", "iso" => "yo", "ar_name" => "اليوروبا"],
            ["en_name" => "Zhuang, Chuang", "iso" => "za", "ar_name" => "تشوانغ، تشوانغ"],
            ["en_name" => "Zulu", "iso" => "zu", "ar_name" => "الزولو"],
        ];
        $languages = [];
        foreach ($all_languages as $lang) {
            $languages[] = ['name' => json_encode(['en' => $lang['en_name'], 'ar' => $lang['ar_name']]), 'iso_code' => $lang['iso'], 'is_site_locale' => $lang['en_name'] == 'English' || $lang['en_name'] == 'Arabic' ? true : false];
        }
        Language::query()->insert($languages);
    }
}
