<?php

namespace App\Filament\Resources\AdminResource\Pages;

use App\Filament\Resources\AdminResource;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Role;

class CreateAdmin extends CreateRecord
{
    protected static string $resource = AdminResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['is_admin'] = true;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function handleRecordCreation(array $data): Model
    {

        $role = Role::query()->find($data['role']);

        return User::create(['name' => $data['name'], 'email' => $data['email'], 'password' => $data['password']]);
//        $admin->assignRole($role);
//        return $admin;
//        dd($role->name);
//
//        dump($data);
//        unset($data['role']);

//        dd($data);
//        dd($data);
//        $admin = ;


//        return;
    }


}
